version: 2
updates:
  - package-ecosystem: "npm"        # must be exactly "npm"
    directory: "/"                  # location of package.json
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "next"
        versions: ["16.x"]
